import os

class Config:
    SECRET_KEY = os.getenv('SECRET_KEY', 'XXXXXXXX')
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL', 'XXXXXXXX')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', 'XXXXXXXXXXX')